# Server Configuration
server:
  port: "8080"
  mode: "debug"
logger:
  level: "info"
  format: "json"

# --- Client & Routing ---

# `apiKeys`: Defines clients allowed to call this API (incoming).
apiKeys:
  - key: "SECRET_KEY_FOR_CLIENT_A"
    clientName: "Client A"
    status: "active"
    permissions:
      - "POST:/api/customer/getcustomerinfo"
      - "POST:/api/customer/updateaddress"
      - "GET:/api/products/*proxyPath"
      
  - key: "SECRET_KEY_FOR_CLIENT_ฺB"
    clientName: "Client B"
    status: "active"
    permissions:
      - "POST:/api/customer/getcustomerinfo"

  - key: ""
    clientName: "for Test"
    status: "active"
    permissions:
      - "POST:/api/customer/getcustomerinfo004"

# `destinations`: Defines outgoing destination and path.
destinations:
  connectorapi:
    type: "http"
    host: "http://localhost:8004/api"
    apiKey: "GW_KEY_FOR_CUST_SVC"

  productService:
    type: "http"
    host: "http://localhost:8002"
    apiKey: "GW_KEY_FOR_PRODUCT_SVC"

  inventoryService:
    type: "tcp"
    host: "localhost:9001"
    apiKey: ""

  SystemIService:
    type: "tcp"
    host: "192.168.129.2:40110"
    apiKey: ""

# `routes`: Maps incoming paths to a destination.
routes:
  "POST:/api/customer/getcustomerinfo":
    destinationName: "connectorapi"
    path: "/customer/getcustomerinfo"

  "POST:/api/customer/updateaddress":
    destinationName: "connectorapi"
    path: "/customer/updateaddress"

  "GET:/api/products/*proxyPath":
    destinationName: "productService"

  "POST:/api/customer/getcustomerinfo004":
    destinationName: "connectorapi"
    path: "/customer/getcustomerinfo004"