# Server Configuration
server:
  port: "8080"
  mode: "debug"
logger:
  level: "info"
  format: "json"

# --- Client & Routing ---

# `apiKeys`: Defines clients allowed to call this API (incoming).
apiKeys:
  - key: "SECRET_KEY_FOR_CLIENT_A"
    clientName: "Client A"
    status: "active"
    permissions:
      - "POST:/api/customer/getcustomerinfo"
      - "POST:/api/customer/updateaddress"
      - "GET:/api/products/*proxyPath"
      
  - key: "SECRET_KEY_FOR_CLIENT_ฺB"
    clientName: "Dept Mediation"
    status: "active"
    permissions:
      - "POST:/Api/Collection/CollectionDetail"
  
  - key: "SECRET_KEY_FOR_CLIENT_ฺB"
    clientName: "Dept Mediation"
    status: "active"
    permissions:
      - "POST:/Api/Collection/CollectionLog"

# `destinations`: Defines outgoing destination and path.
destinations:
  systemi:
    type: "tcp"
    host: "192.168.129.2:40110"
    apiKey: ""

# `routes`: Maps incoming paths to a destination.
routes:
  "POST:/api/customer/getcustomerinfo":
    System: "MOB_APP"         
    Service: "INQ_CUST_INFO"  
    Format: "004"             

  "POST:/api/customer/updateaddress":
    System: "MOB_APP"
    Service: "UPD_CUST_INFO"
    Format: "001"
  
  "POST:/Api/collection/CollectionDetail":
    System:   "AEON_WF"
    Service:  "INQ_CUST_CISINF"
    Format:   "001"

  "POST:/Api/collection/CollectionLog":
    System:   "AEON_WF"
    Service:  "UPD_CUST_COSRMK"
    Format:   "001"