basePath: /api
definitions:
  domain.Address:
    properties:
      city:
        type: string
      postalCode:
        type: string
      street:
        type: string
    required:
    - city
    - postalCode
    - street
    type: object
  domain.ErrorResponse:
    properties:
      ErrorCode:
        type: string
      ErrorMessage:
        type: string
      Request_ID:
        type: string
      Status:
        type: integer
      Timestamp:
        type: string
    type: object
  domain.GetCustomerInfoRequest:
    properties:
      aeonid:
        type: string
      agreementno:
        type: string
      idcardno:
        type: string
    type: object
  domain.GetCustomerInfoResponse:
    properties:
      aeonid:
        type: string
      customernameeng:
        type: string
      customernameth:
        type: string
      dateofbirth:
        type: string
      email:
        type: string
      memberstatus:
        type: string
      mobileno:
        type: string
      nationality:
        type: string
      sex:
        type: string
    type: object
  domain.UpdateAddressRequest:
    properties:
      address:
        $ref: '#/definitions/domain.Address'
      customerId:
        type: string
    required:
    - address
    - customerId
    type: object
  domain.UpdateAddressResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: sye@aeon.co.th
    name: SYE
    url: https://aeon.co.th
  description: This is a sample API documentation for our Go API application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Template Go API
  version: "1.0"
paths:
  /customer/getcustomerinfo:
    post:
      consumes:
      - application/json
      description: retrieves customer details based on customer ID and channel
      parameters:
      - description: Client's API Key
        in: header
        name: API-Key
        required: true
        type: string
      - description: Client's Request ID
        in: header
        name: RequestID
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetCustomerInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetCustomerInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get Customer Information format 004
      tags:
      - Customer
  /customer/updateaddress:
    post:
      consumes:
      - application/json
      description: update customer address from request
      parameters:
      - description: Client's API Key
        in: header
        name: API-Key
        required: true
        type: string
      - description: Client's Request ID
        in: header
        name: RequestID
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateAddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UpdateAddressResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Update Customer Address
      tags:
      - Customer
swagger: "2.0"
